/// <reference path="globals/colors.d.ts" />
/// <reference path="globals/colours.d.ts" />
/// <reference path="globals/commands.d.ts" />
/// <reference path="globals/disk.d.ts" />
/// <reference path="globals/fs.d.ts" />
/// <reference path="globals/global.d.ts" />
/// <reference path="globals/gps.d.ts" />
/// <reference path="globals/help.d.ts" />
/// <reference path="globals/http.d.ts" />
/// <reference path="globals/keys.d.ts" />
/// <reference path="globals/multishell.d.ts" />
/// <reference path="globals/os.d.ts" />
/// <reference path="globals/paintutils.d.ts" />
/// <reference path="globals/parallel.d.ts" />
/// <reference path="globals/peripheral.d.ts" />
/// <reference path="globals/pocket.d.ts" />
/// <reference path="globals/rednet.d.ts" />
/// <reference path="globals/redstone.d.ts" />
/// <reference path="globals/settings.d.ts" />
/// <reference path="globals/shell.d.ts" />
/// <reference path="globals/term.d.ts" />
/// <reference path="globals/textutils.d.ts" />
/// <reference path="globals/turtle.d.ts" />
/// <reference path="globals/vector.d.ts" />
/// <reference path="globals/window.d.ts" />

/// <reference path="../cc-types-base/index.d.ts"/>
